<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <UseWPF>true</UseWPF>
        <PublishSingleFile>true</PublishSingleFile>
        <AssemblyTitle>Night Ember</AssemblyTitle>
        <Product>Night Ember</Product>
        <Copyright>Austin S.</Copyright>
        <Description>A portable night-light application for Windows.</Description>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="H.NotifyIcon.Wpf" Version="2.4.1"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="$(AssemblyName).Tests.Unit"/>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\AppIcon.ico"/>
    </ItemGroup>
</Project>
